# Change these first
owner: njculver # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Minecraft
    url: $MINECRAFT_URL
    port: 25565
    check: "tcp-ping"
  # - name: Project Zomboid
  #   url: $ZOMBOID_URL
  #   port: 16261
  #   check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.nicholasculver.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: See below for game server status - ask for the URLs!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "0 0 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
